load("deno_test.bzl", "deno_test")
load("nodejs_test.bzl", "nodejs_test")
load("python_test.bzl", "python_test")
load("java_test.bzl", "java_test")
load("base_test.bzl", "base_test")
load("cc_test.bzl", "cc_test")
load("static_test.bzl", "static_test")

base_test()

cc_test()

java_test()

python_test()

nodejs_test()

deno_test()
