core:
  - 'deps/ubuntu/**'
  - 'deps/core/**'
  - 'layer/static/**'
  - 'layer/base/**'
  - 'layer/cc/**'
  - 'layer/python/**'
  - 'test/*.yaml'
java:
  - 'ext/adoptium/**'
  - 'ext/azul/**'
  - 'deps/java/**'
  - 'layer/java/**'
  - 'image/java/**'
  - 'image/javapy/**'
  - 'test/java/**'
deno:
  - 'ext/deno/**'
  - 'deps/deno/**'
  - 'layer/deno/**'
  - 'image/deno/**'
  - 'test/deno/**'
nodejs:
  - 'ext/nodejs/**'
  - 'deps/nodejs/**'
  - 'layer/nodejs/**'
  - 'image/nodejs/**'
  - 'test/nodejs/**'
trino:
  - 'ext/trino/**'
  - 'deps/trino/**'
  - 'layer/trino/**'
  - 'image/trino/**'
  - 'test/trino/**'
spark:
  - 'ext/spark/**'
  - 'deps/spark/**'
  - 'layer/spark/**'
  - 'image/spark/**'
  - 'test/spark/**'
hive:
  - 'ext/hivemetastore/**'
  - 'ext/hadoop/**'
  - 'deps/hive/**'
  - 'deps/hadoop/**'
  - 'layer/hivemetastore/**'
  - 'image/hivemetastore/**'
  - 'test/hivemetastore/**'