= Yet Another Distroless

Yet Another Distroless (or YAD) is based on the existing Distroless distribution  maintained by the GoogleContainerTools team (https://github.com/GoogleContainerTools/distroless).

YAD differs from the distroless distribution on the following :

- The package manager used is rules_deb_packages (https://github.com/petermylemans/rules_deb_packages)
- The linux distribution tracked is the Ubuntu one. For now we only track the Ubuntu focal (Focal Fossa). Other Ubuntu release later may be added.

== Why Distroless ?

Distroless are container restricting to what the application only need to run. It improves the maintenance of the dependencies and the overall security by removing all the software not needed

== How do use the images ?

The images are published on docker registry : https://hub.docker.com/u/yadist

You can use these images like any other Docker images.

The images are build for amd64 and arm64 architectures

=== Entrypoints

Most of the distroless image does not contain a shell. That means the Dockerfile `ENTRYPOINT` command, when defined, must be specified in `vector` form, to avoid the container runtime prefixing with a shell.

This works:

[source,dockerfile]
----
ENTRYPOINT ["myapp"]
----

But this does not work:

[source,dockerfile]
----
ENTRYPOINT "myapp"
----

For the same reasons, if the entrypoint is left to the default empty vector, the CMD command should be specified in `vector` form.

=== Images List

==== Base

.Base Image List
[cols=".^10%,15%,15%,60%",width="100%",options="header"]
|===

| Image 
^| Ubuntu Bionic
^| Ubuntu Focal  
| Usage

| link:image/static/README.md[static]
| image:https://img.shields.io/docker/image-size/yadist/static/bionic?label=bionic&logo=docker[link="https://hub.docker.com/r/yadist/static/"]
| image:https://img.shields.io/docker/image-size/yadist/static/focal?label=focal&logo=docker[link="https://hub.docker.com/r/yadist/static/"]
| For running staticaly linked application

| link:image/base/README.md[base]
| image:https://img.shields.io/docker/image-size/yadist/base/bionic?label=bionic&logo=docker[link="https://hub.docker.com/r/yadist/base/"]
| image:https://img.shields.io/docker/image-size/yadist/base/focal?label=focal&logo=docker[link="https://hub.docker.com/r/yadist/base/"]
| For running libc and openssl dynamically linked application

| link:image/cc/README.md[cc]
| image:https://img.shields.io/docker/image-size/yadist/cc/bionic?label=bionic&logo=docker[link="https://hub.docker.com/r/yadist/cc/"]
| image:https://img.shields.io/docker/image-size/yadist/cc/focal?label=focal&logo=docker[link="https://hub.docker.com/r/yadist/cc/"]
| For running libc, libgcc and openssl linked application

| link:image/python/README.md[python]
| image:https://img.shields.io/docker/image-size/yadist/python/bionic?label=bionic&logo=docker[link="https://hub.docker.com/r/yadist/python/"]
| image:https://img.shields.io/docker/image-size/yadist/python/focal?label=focal&logo=docker[link="https://hub.docker.com/r/yadist/python/"]
| For running python application(python 3.x)
|===

==== Java

.Java Image List
[cols=".^10%,15%,15%,60%",width="100%",options="header"]
|===

| Image 
^| Ubuntu Bionic
^| Ubuntu Focal  
| Usage

| link:image/java/README.md[adoptium]
| image:https://img.shields.io/docker/image-size/yadist/adoptium/8_bionic?label=8_bionic&logo=docker[link="https://hub.docker.com/r/yadist/adoptium/"]
image:https://img.shields.io/docker/image-size/yadist/adoptium/11_bionic?label=11_bionic&logo=docker[link="https://hub.docker.com/r/yadist/adoptium/"]
image:https://img.shields.io/docker/image-size/yadist/adoptium/17_bionic?label=17_bionic&logo=docker[link="https://hub.docker.com/r/yadist/adoptium/"]
| image:https://img.shields.io/docker/image-size/yadist/adoptium/8_focal?label=8_focal&logo=docker[link="https://hub.docker.com/r/yadist/adoptium/"]
image:https://img.shields.io/docker/image-size/yadist/adoptium/11_focal?label=11_focal&logo=docker[link="https://hub.docker.com/r/yadist/adoptium/"]
image:https://img.shields.io/docker/image-size/yadist/adoptium/17_focal?label=17_focal&logo=docker[link="https://hub.docker.com/r/yadist/adoptium/"]
|  For running java application with https://adoptium.net/[adoptium] jre

| link:image/javapy/README.md[adoptiumpy]
| image:https://img.shields.io/docker/image-size/yadist/adoptiumpy/8_bionic?label=8_bionic&logo=docker[link="https://hub.docker.com/r/yadist/adoptiumpy/"]
image:https://img.shields.io/docker/image-size/yadist/adoptiumpy/11_bionic?label=11_bionic&logo=docker[link="https://hub.docker.com/r/yadist/adoptiumpy/"]
image:https://img.shields.io/docker/image-size/yadist/adoptiumpy/17_bionic?label=17_bionic&logo=docker[link="https://hub.docker.com/r/yadist/adoptiumpy/"]
| image:https://img.shields.io/docker/image-size/yadist/adoptiumpy/8_focal?label=8_focal&logo=docker[link="https://hub.docker.com/r/yadist/adoptiumpy/"]
image:https://img.shields.io/docker/image-size/yadist/adoptiumpy/11_focal?label=11_focal&logo=docker[link="https://hub.docker.com/r/yadist/adoptiumpy/"]
image:https://img.shields.io/docker/image-size/yadist/adoptiumpy/17_focal?label=17_focal&logo=docker[link="https://hub.docker.com/r/yadist/adoptiumpy/"]
|  For running java application with https://adoptium.net/[adoptium] jre and python dependencies

| link:image/java/README.md[azul]
| image:https://img.shields.io/docker/image-size/yadist/azul/8_bionic?label=8_bionic&logo=docker[link="https://hub.docker.com/r/yadist/azul/"]
image:https://img.shields.io/docker/image-size/yadist/azul/11_bionic?label=11_bionic&logo=docker[link="https://hub.docker.com/r/yadist/azul/"]
image:https://img.shields.io/docker/image-size/yadist/azul/17_bionic?label=17_bionic&logo=docker[link="https://hub.docker.com/r/yadist/azul/"]
| image:https://img.shields.io/docker/image-size/yadist/azul/8_focal?label=8_focal&logo=docker[link="https://hub.docker.com/r/yadist/azul/"]
image:https://img.shields.io/docker/image-size/yadist/azul/11_focal?label=11_focal&logo=docker[link="https://hub.docker.com/r/yadist/azul/"]
image:https://img.shields.io/docker/image-size/yadist/azul/17_focal?label=17_focal&logo=docker[link="https://hub.docker.com/r/yadist/azul/"]
|  For running java application with https://azul.com/[azul] jre

| link:image/javapy/README.md[azulpy]
| image:https://img.shields.io/docker/image-size/yadist/azulpy/8_bionic?label=8_bionic&logo=docker[link="https://hub.docker.com/r/yadist/azulpy/"]
image:https://img.shields.io/docker/image-size/yadist/azulpy/11_bionic?label=11_bionic&logo=docker[link="https://hub.docker.com/r/yadist/azulpy/"]
image:https://img.shields.io/docker/image-size/yadist/azulpy/17_bionic?label=17_bionic&logo=docker[link="https://hub.docker.com/r/yadist/azulpy/"]
| image:https://img.shields.io/docker/image-size/yadist/azulpy/8_focal?label=8_focal&logo=docker[link="https://hub.docker.com/r/yadist/azulpy/"]
image:https://img.shields.io/docker/image-size/yadist/azulpy/11_focal?label=11_focal&logo=docker[link="https://hub.docker.com/r/yadist/azulpy/"]
image:https://img.shields.io/docker/image-size/yadist/azulpy/17_focal?label=17_focal&logo=docker[link="https://hub.docker.com/r/yadist/azulpy/"]
|  For running java application with https://azul.com/[azul] jre and python dependencies
|===

==== Typescript

.Typescript Image List
[cols=".^10%,15%,15%,60%",width="100%",options="header"]
|===

| Image 
^| Ubuntu Bionic
^| Ubuntu Focal  
| Usage

| link:image/nodejs/README.md[nodejs]
| image:https://img.shields.io/docker/image-size/yadist/nodejs/14_bionic?label=14_bionic&logo=docker[link="https://hub.docker.com/r/yadist/nodejs/"]
image:https://img.shields.io/docker/image-size/yadist/nodejs/16_bionic?label=16_bionic&logo=docker[link="https://hub.docker.com/r/yadist/nodejs/"]
| image:https://img.shields.io/docker/image-size/yadist/nodejs/14_focal?label=14_focal&logo=docker[link="https://hub.docker.com/r/yadist/nodejs/"]
image:https://img.shields.io/docker/image-size/yadist/nodejs/16_focal?label=16_focal&logo=docker[link="https://hub.docker.com/r/yadist/nodejs/"]
| For running javascript application

| link:image/deno/README.md[deno] | image:https://img.shields.io/docker/image-size/yadist/deno/bionic?label=bionic&logo=docker[link="https://hub.docker.com/r/yadist/deno/"] | image:https://img.shields.io/docker/image-size/yadist/deno/focal?label=focal&logo=docker[link="https://hub.docker.com/r/yadist/deno/"] | For running typescript application 
|===

==== Big Data

.Big Data Image List
[cols=".^10%,15%,15%,60%",width="100%",options="header"]
|===

| Image 
^| Ubuntu Bionic
^| Ubuntu Focal  
| Usage

| link:image/spark/README.md[spark]
| image:https://img.shields.io/docker/image-size/yadist/spark/2.4?label=2.4&logo=docker[link="https://hub.docker.com/r/yadist/spark/"]
| image:https://img.shields.io/docker/image-size/yadist/spark/3.0?label=3.0&logo=docker[link="https://hub.docker.com/r/yadist/spark/"]
image:https://img.shields.io/docker/image-size/yadist/spark/3.1?label=3.1&logo=docker[link="https://hub.docker.com/r/yadist/spark/"]
image:https://img.shields.io/docker/image-size/yadist/spark/3.2?label=3.2&logo=docker[link="https://hub.docker.com/r/yadist/spark/"]
| For running spark application

| link:image/spark/README.md[pyspark]
| image:https://img.shields.io/docker/image-size/yadist/pyspark/2.4?label=2.4&logo=docker[link="https://hub.docker.com/r/yadist/pyspark/"]
| image:https://img.shields.io/docker/image-size/yadist/pyspark/3.0?label=3.0&logo=docker[link="https://hub.docker.com/r/yadist/pyspark/"]
image:https://img.shields.io/docker/image-size/yadist/pyspark/3.1?label=3.1&logo=docker[link="https://hub.docker.com/r/yadist/pyspark/"]
image:https://img.shields.io/docker/image-size/yadist/pyspark/3.2?label=3.2&logo=docker[link="https://hub.docker.com/r/yadist/pyspark/"]
| For running pyspark application

| link:image/spark/README.md[sparkhistoryserver]
| image:https://img.shields.io/docker/image-size/yadist/sparkhistoryserver/2.4?label=2.4&logo=docker[link="https://hub.docker.com/r/yadist/sparkhistoryserver/"]
| image:https://img.shields.io/docker/image-size/yadist/sparkhistoryserver/3.0?label=3.0&logo=docker[link="https://hub.docker.com/r/yadist/sparkhistoryserver/"]
image:https://img.shields.io/docker/image-size/yadist/sparkhistoryserver/3.1?label=3.1&logo=docker[link="https://hub.docker.com/r/yadist/sparkhistoryserver/"]
image:https://img.shields.io/docker/image-size/yadist/sparkhistoryserver/3.2?label=3.2&logo=docker[link="https://hub.docker.com/r/yadist/sparkhistoryserver/"]
| For running the spark historyserver application

| link:image/hive/README.md[hivemetastore]
| 
| image:https://img.shields.io/docker/image-size/yadist/hivemetastore/latest?label=latest&logo=docker[link="https://hub.docker.com/r/yadist/hivemetastore/"]
| For running the hive metastore server

| link:image/trino/README.md[trino]
| 
| image:https://img.shields.io/docker/image-size/yadist/trino/latest?label=latest&logo=docker[link="https://hub.docker.com/r/yadist/trino/"]
| For running the trino server

|===

==== Database

.Database Image List
[cols=".^10%,15%,15%,60%",width="100%",options="header"]
|===

| Image 
^| Ubuntu Bionic
^| Ubuntu Focal  
| Usage

| link:image/mariadb/README.md[Mariadb]
| image:https://img.shields.io/docker/image-size/yadist/mariadb/10.5_bionic?label=10.5&logo=docker[link="https://hub.docker.com/r/yadist/mariadb/"]
image:https://img.shields.io/docker/image-size/yadist/mariadb/10.6_bionic?label=10.6&logo=docker[link="https://hub.docker.com/r/yadist/mariadb/"]
image:https://img.shields.io/docker/image-size/yadist/mariadb/10.7_bionic?label=10.7&logo=docker[link="https://hub.docker.com/r/yadist/mariadb/"]
| image:https://img.shields.io/docker/image-size/yadist/mariadb/10.5?label=10.5&logo=docker[link="https://hub.docker.com/r/yadist/mariadb/"]
image:https://img.shields.io/docker/image-size/yadist/mariadb/10.6?label=10.6&logo=docker[link="https://hub.docker.com/r/yadist/mariadb/"]
image:https://img.shields.io/docker/image-size/yadist/mariadb/10.7?label=10.7&logo=docker[link="https://hub.docker.com/r/yadist/mariadb/"]
| For running consult template

|===

==== Utils

.Utils Image List
[cols=".^10%,15%,15%,60%",width="100%",options="header"]
|===

| Image 
^| Ubuntu Bionic
^| Ubuntu Focal  
| Usage

| link:image/consultemplate/README.md[Consul Template]
| 
| image:https://img.shields.io/docker/image-size/yadist/consultemplate/latest?label=latest&logo=docker[link="https://hub.docker.com/r/yadist/consultemplate/"]
| For running consult template

| link:image/prometheus/README.md[prometheus]
| 
| image:https://img.shields.io/docker/image-size/yadist/prometheus/latest?label=latest&logo=docker[link="https://hub.docker.com/r/yadist/prometheus/"]
| For running prometheus

| link:image/prometheus/README.md[nodeexporter]
| 
| image:https://img.shields.io/docker/image-size/yadist/nodeexporter/latest?label=latest&logo=docker[link="https://hub.docker.com/r/yadist/nodeexporter/"]
| For running node exporter

|===

Most of the images have a variant with busybox bundled. Theese images are identified with a "_debug" suffix on the tag.

=== Security

The dependencies are updated daily and new images are released as soon as the dependencies are updated. We rely on CVE security release handled bu Ubuntu (https://ubuntu.com/security/cve) for Ubuntu packages.

For Azul JRE we rely on Azul security release (https://docs.azul.com/core/cve) 

