name: Deploy

on:
  push:
    branches: [ main]
  workflow_dispatch:
jobs:
  deploy:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Free space
        run : |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD', '**/*.bzl', 'WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-bazel-ci-
            ${{ runner.os }}-bazel-
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: bazel test
        run: |
          bazel test --config x86_64 -c opt //test:images //test:images_amd64_only
          bazel test --config x86_64 -c dbg //test:images //test:images_amd64_only
          bazel test --config arm64 -c opt //test:images
          bazel test --config arm64 -c dbg //test:images
      - name: bazel publish
        run: |
          bazel run --config x86_64 -c opt //image:push
          bazel run --config x86_64 -c dbg //image:push
          bazel run --config arm64 -c opt //image:push
          bazel run --config arm64 -c dbg //image:push
      - name: merge tags
        run: hack/merge_tag.sh docker.io
  sign:
    environment: Release
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.1.0'
      - name: cosign image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: hack/cosign.sh docker.io
