name: First Build

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD', '**/*.bzl', 'WORKSPACE') }}
      - name: bazel clean
        run: bazel clean
      - name: bazel build
        run: bazel build //image:all

