name: Launch Test

on:
  pull_request:
    types: [ready_for_review]
  workflow_dispatch:

jobs:
  test:
    environment: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-${{ hashFiles('**/BUILD', '**/*.bzl', 'WORKSPACE') }}
      - name: bazel test
        run: bazel test //test:*
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: testLogs
          path: /home/runner/.cache/bazel/_bazel_runner/**/execroot/yad/bazel-out/k8-fastbuild/testlogs/test/**/test.log

