name: Build

on:
  pull_request:
    types: [synchronize, opened, reopened]
  workflow_dispatch:

jobs:
  build:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-ci-${{ hashFiles('**/BUILD', '**/*.bzl', 'WORKSPACE') }}
          restore-keys: |
            ${{ runner.os }}-bazel-clean-${{ steps.date.outputs.date }}
            ${{ runner.os }}-bazel-ci-
            ${{ runner.os }}-bazel-
      - name: bazel build
        run: bazel build //image:all
      - name: bazel test
        run: bazel test //test:*
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: testLogs
          path: /home/runner/.cache/bazel/_bazel_runner/**/execroot/yad/bazel-out/k8-fastbuild/testlogs/test/**/test.log