name: Clean cache

on:
  workflow_dispatch:

jobs:
  clean:
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Mount bazel cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: ${{ runner.os }}-bazel-clean-${{ steps.date.outputs.date }}
          restore-keys: |
            ${{ runner.os }}-bazel-ci-
            ${{ runner.os }}-bazel-
      - name: bazel clean
        run: rm -fr ~/.cache/bazel

