name: update-security
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'
    
jobs:
  build:
    environment: Release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      security-events: write
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Run trivy scan
        run : |
          hack/security_scan.sh jammy
          hack/security_scan.sh bionic
          hack/security_scan.sh focal
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: 'security/sarif'
      # - name: Delete sarif folder
      #   run: rm -f security/sarif/*.sarif
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Update : security scans"
          title: "Updating security scans"
          body: "Automatic scheduled task. Launch Security scans and upload them"
          branch: "update-security"
          author: y0psolo <lionel.herbet@gmail.com>
          delete-branch: true
          draft: true
          labels: |
            security
            automated
          assignees: y0psolo
          reviewers: y0psolo
