name: update-deps
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1
      - name: Run update scripts
        run: |
          bazel run :update_jammy_packages
          bazel run :update_focal_packages
          bazel run :update_bionic_packages
          update/ld_cache_gen.sh
          update/update_azul.sh
          update/update_adoptium.sh
          update/update_nodejs.sh
          update/update_deno.sh
          update/update_hadoop.sh
          update/update_hive.sh
          update/update_spark.sh
          update/update_trino.sh
          update/update_redis.sh
          update/update_consultemplate.sh
          update/update_mariadb.sh
          update/update_prometheus.sh
          bazel run :update_deno
          bazel run :update_java
          bazel run :update_nodejs
          bazel run :update_hadoop
          bazel run :update_hive
          bazel run :update_spark
          bazel run :update_trino
          bazel run :update_redis
          bazel run :update_consultemplate
          bazel run :update_mariadb
          bazel run :update_prometheus
          bazel run :update_versions
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Bumping packages to last version"
          title: "Bumping packages to last version"
          body: "Automatic scheduled task. Check packages version and bump them"
          branch: "update-deps"
          author: y0psolo <lionel.herbet@gmail.com>
          delete-branch: true
          draft: true
          labels: |
            update
            automated
          assignees: y0psolo
          reviewers: y0psolo